import Head from "next/head";
import Image from "next/image";
import About from "../components/About";
import Business from "../components/Business";
import Header from "../components/Header";
import Hero from "../components/Hero";
import Projects from "../components/Projects";
import Contact from "./contact";

export default function Home() {
  return (
    <div className=" md:flex md:flex-col md:items-center md:justify-center ">
      <Head>
        <title>Khushaal Choithramani</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <Hero />
      <About />
      <Business />
      <Projects />
      <Contact />
    </div>
  );
}
